name: demo1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  #for design
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.0+1
  smooth_page_indicator: ^1.0.1
  image_picker: ^0.8.6+1
  lottie: ^2.2.0
  linear_timer: ^2.0.0
  smooth_star_rating_null_safety: ^1.0.4+2


  #map_launcher:
  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2


  #locale storage
  shared_preferences: ^2.0.17


  #printing:
  l: ^3.2.0


  #localization:
  easy_localization: ^3.0.1


  #stateManagment
  flutter_riverpod: ^2.2.0


  #toast
  fluttertoast: ^8.1.1

  #bottomSheet
  draggable_home: ^1.0.4

  flutter_timer_countdown: ^1.0.5

  #http
  http: ^0.13.5
  http_interceptor: ^1.0.2


dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/intro_page/
    - assets/images/intro_page/chikki_logo.png
    - assets/images/login/
    - assets/images/home/
    - assets/images/order/
    - assets/translations/
    - assets/icons/login/
    - assets/icons/order/
    - assets/icons/home/
    - assets/icons/choose_car/
    - assets/lottle/
    - assets/images/order/
    #food
    - assets/images/food/food_home/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
